In [4]:
import random
import time
import numpy as np


a = []
t0 = time.time()
for i in range(10000000):
    a.append(random.random())
    
t1 = time.time()
sum1=sum(a)
t2=time.time()


b=np.array(a)
t4=time.time()
sum3=np.sum(b)
t5=time.time()
print(t1-t0,t2-t1, t5-t4)

3.8821024894714355 0.12798023223876953 0.02200484275817871


In [5]:
lst1 = [1,2,3,4]
nar = np.array(lst1)
print(type(nar), nar)

<class 'numpy.ndarray'> [1 2 3 4]


In [6]:
nar1 = np.array(range(10))
print(nar1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
nar2 = np.arange(0,10,2)
print(type(nar2), nar2)

<class 'numpy.ndarray'> [0 2 4 6 8]


In [15]:
nda = np.array([[1,2],[3,4],[8,9]])
print(nda.ndim)
print(nda.size)
print(nda.shape, type(nda.shape))


2
6
(3, 2) <class 'tuple'>


In [21]:
four = np.array([[1,2,3],[4,5,6]])
print(four)
print(four.shape)
four.shape = (3,2) 
print(four)
print(four.shape)

six = four
print(six is four)
five = four.reshape(3,2)
print(five is four)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
True
False


In [34]:
four = np.array([[1,2,3],[4,5,6]])
five = four.reshape((6,),order='C')
print(five)

six = four.flatten(order='F')
print(six)



[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [38]:
t = np.arange(24)
t1 = t.reshape(4,6)
# print(t1)

t2 = t.reshape((2,3,4))
# t2 = t.reshape(2,3,4)
print(t2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
a = np.array([1,34,4])
b = a.tolist()
print(type(a),type(b))

print(a)
print(b)

<class 'numpy.ndarray'> <class 'list'>
[ 1 34  4]
[1, 34, 4]


In [55]:
f = np.array([1,2,3,4,5], dtype=np.int16)
print(f.itemsize)
print(f.dtype)

f1 = f.astype(np.int64)
print(f1.dtype)


print(round(random.random(), 2))
arr = np.array([random.random() for i in range(10)])
print(arr)
arr2 = np.round(arr,2)


print(arr2)
print(arr is arr2)

2
int16
int64
0.02
[0.86586536 0.29565881 0.1836054  0.44626674 0.26901334 0.02483189
 0.30408559 0.53414897 0.92462966 0.72379604]
[0.87 0.3  0.18 0.45 0.27 0.02 0.3  0.53 0.92 0.72]
False


In [65]:
t1 =  np.arange(24).reshape(6,4)
t2 = t1 * 2
print(t1 is t2)
print(t1)
print(t2)

False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [69]:
t1 = np.arange(24).reshape(6,4)
t2 = np.arange(100,124).reshape(3,4)

print(t1+t2)
print(t1*t2)

ValueError: cannot reshape array of size 24 into shape (3,4)

In [76]:
t1 = np.arange(24).reshape(4,6)
t2 = np.arange(0,6)
print(t1)
# print(t1.shape)
print(t2)
# print(t2.shape)

print(t1 - t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [77]:
t1 = np.arange(24).reshape(4,6)
t2 = np.arange(4).reshape(4,1)
print(t1)
# print(t1.shape)
print(t2)
# print(t2.shape)

print(t1 - t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [80]:
a = np.arange(10)
print(a[2:7:2])
print(a[2],a)
print(a[2:])

[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [95]:
t1 = np.arange(24 ).reshape(4,6)
print(t1)
print('*'*20)
# print(t1[1])
# print(t1[1,:])
# print(t1[1:3,:])

# print(t1[[0,2,3]])
# print(t1[:,1:])
# print(t1[:, [0,2,3]])
# print(t1[2,3])
print(t1[[0,1,1],[0,1,3]])


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[0 7 9]


In [100]:
t1 = np.arange(24 ).reshape(4,6)
print(t1)
print('*'*20)
t1[:,1] = 0
t1[t1<10] = 0
print(t1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 11]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]


In [106]:
# 添加

a = np.array([[1,2,3],[4,5,6]])
print(a)
print('*'*20)

# b = np.append(a, [7,8,9])
# print(a is b )
# print(a)
# print('*'*20)
# print(b)

print(np.append(a, [[7,8,9]], axis = 0))
print('*'*20)
print(np.append(a, [[5,5,5],[6,6,6]], axis = 1))

[[1 2 3]
 [4 5 6]]
********************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************
[[1 2 3 5 5 5]
 [4 5 6 6 6 6]]


In [112]:
#　insert
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print('*'*20)

# b = np.insert(a, 3, [11,12])
# print(a is b)
# print(b)
print(np.insert(a, 1, 11, axis = 0))
print('*'*20)
print(np.insert(a, 1, [11], axis = 0))
print('*'*20)
print(np.insert(a, 1, [11], axis = 1))
print('*'*20)
print(np.insert(a, 1, 11, axis = 1))

[[1 2]
 [3 4]
 [5 6]]
********************
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
********************
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
********************
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
********************
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [114]:
# 删除
a = np.arange(12).reshape(3,4)
print(a)
print('*'*20)

# print(np.delete(a,5))
print(np.delete(a,1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
********************
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [126]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)
print('*'*20)

# print(np.unique(a))
u,indices = np.unique(a, return_index=True)

print(u)
print('*'*20)
print(indices) 
print('*'*20)
print('*'*20)
u,indices = np.unique(a, return_inverse=True)
print(u)
print('*'*20)
print(indices) 

[5 2 6 2 7 5 6 8 2 9]
********************
[2 5 6 7 8 9]
********************
[1 0 2 4 7 9]
********************
********************
[2 5 6 7 8 9]
********************
[1 0 2 0 3 1 2 4 0 5]


In [127]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)
print('*'*20)
u,indices = np.unique(a, return_counts = True)
print(u)
print(indices)

[5 2 6 2 7 5 6 8 2 9]
********************
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [133]:
#numpy 的计算
score = np.array([[80,88],[82,81],[75,81]])
print(score)

# result = np.max(score)
# print(result)
result = np.max(score, axis = 0)
print(result)

result = np.max(score, axis = 1)
print(result)

[[80 88]
 [82 81]
 [75 81]]
[82 88]
[88 82 81]


In [154]:
#numpy 的计算
score = np.array([[83,88],[82,81],[75,81]])
print(score)
print('*'*20)

# print(np.maximum([-2,-1,0,1,2],0))
# print(np.minimum([-2,-1,0,1,2],0))
# print(np.maximum([2,-1,0,1,2],[1,2,3,4,5]))
# print(np.mean(score))
# print(np.mean(score, axis=0))

print(np.min(socre,axis = 0))
print(np.argmin(score, axis=0))
# print(np.argmax(score, axis=0))w

[[83 88]
 [82 81]
 [75 81]]
********************
[75 81]
[2 1]


In [148]:
arr = np.array([[1,2,3], [4,5,6],[8,8,8]])
print(arr)
print(arr.cumsum(0))
print(arr.cumsum(1))

[[1 2 3]
 [4 5 6]
 [8 8 8]]
[[ 1  2  3]
 [ 5  7  9]
 [13 15 17]]
[[ 1  3  6]
 [ 4  9 15]
 [ 8 16 24]]


In [164]:
# 拼接
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# print(np.concatenate((a,b), axis=0))
# print(np.concatenate((a,b), axis=1))
print(np.stack((a,b), axis = 0))
print('*'*20)
print(np.stack((a,b), axis = 1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
********************
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [168]:
# 矩阵垂直拼接
v1 = [[0,1,2,3,4,5],[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],[18,19,20,21,22,23]]

print(np.stack((v1,v2), axis = 0))
print('*'*20)
print(np.stack((v1,v2), axis = 1))
print('*'*20)
print(np.vstack((v1,v2)))
print('*'*20)
print(np.hstack((v1,v2)))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
********************
[[[ 0  1  2  3  4  5]
  [12 13 14 15 16 17]]

 [[ 6  7  8  9 10 11]
  [18 19 20 21 22 23]]]
********************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [35]:
import numpy as np
# 数组的分隔
arr = np.arange(12).reshape(3,4)
print(arr)

# b = np.split(arr,3)
# print(b)

print(np.split(arr,3,axis = 0))
# print(np.split(arr,4,axis = 1))

# harr = np.floor(10 * np.random.random((2,6)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# print(harr)
# print(np.hsplit(harr,3))

# print(np.hsplit(arr, 4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [31]:
# a = np.arange(16).reshape(4,4)
# print(np.vsplit(a,2))

In [51]:
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

t = np.arange(24,dtype=float).reshape(4,6)
print(np.count_nonzero(t))
t[3,4] = np.nan
print(t)

# print(np.nan == np.nan)
print(np.count_nonzero(t != t))
print(np.sum(t,axis = 0))

t[np.isnan(t)] = 0
print(t)

nan <class 'float'>
inf <class 'float'>
23
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
1
[36. 40. 44. 48. nan 56.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [57]:
t = np.arange(24).reshape(4,6).astype('float')
print(t)
t[1,3:] = np.nan
print(t)


# print(t[np.isnan(t)])

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [61]:
# 二维数组的转置
a = np.arange(12).reshape(3,4)
print(a)
print(np.transpose(a))
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [63]:
t = np.arange(24).reshape(4,6)
re = t.swapaxes(1,0)
print(t)
print('*'*20)
print(re)
print('*'*20)
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
********************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [87]:
c = np.array([2,3])
d = np.array([2,4])
print(sum(c == d))

2
